[theme]
base = "dark"
primaryColor = "#38bdf8"
backgroundColor = "#0a1124"
secondaryBackgroundColor = "#111c38"
textColor = "#ffffff"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
